import random

# Variables with lists of possible elements
adjectives = [
    "mystical",
    "shiny",
    "dark",
    "colorful",
    "tranquil",
    "ancient",
    "futuristic",
    "vibrant",
    "dystopian",
    "serene",
    "cosmic",
    "dreamy",
    "nebulous",
    "twinkling",
    "ghostly",
    "celestial",
    "rustic",
    "fabled",
    "luminous",
    "mythic",
    "abandoned",
    "floating",
    "mysterious",
    "underwater",
    "forgotten",
    "haunted",
    "space",
    "ethereal",
    "incandescent",
    "melodic",
    "frosty",
    "fiery",
    "shadowy",
    "golden",
    "silvered",
    "arcane",
    "enigmatic",
    "sacred",
    "profane",
    "emerald",
    "crystalline",
    "majestic",
    "regal",
    "ornate",
    "prismatic",
    "opaque",
    "translucent",
    "radiant",
    "gloomy",
    "enchanting",
    "perilous",
    "tempestuous",
    "whimsical",
    "effulgent",
    "phantasmal",
    "auroral",
    "stellar",
    "eclipsing",
    "crescent",
    "bountiful",
    "desolate",
    "verdant",
    "lush",
    "sterling",
    "nautical",
    "aerial",
    "subterranean",
    "alabaster",
    "draconic",
    "spectral",
    "iridescent",
    "kaleidoscopic",
    "dazzling",
    "charmed",
    "bewitching",
    "velvet",
    "silken",
    "coppery",
    "zephyrous",
    "obscure",
    "divine",
    "infernal",
    "terrestrial",
    "aquatic",
    "sylvan",
    "harmonious",
    "discordant",
    "resplendent",
    "ephemeral",
    "eternal",
    "chronal",
    "primordial",
    "arcadian",
    "wondrous",
    "surreal",
    "bizarre",
    "elusive",
    "forged",
    "revered",
    "mythological",
    "legendary",
    "enveloping",
    "shifting",
    "tumultuous",
    "sonorous",
    "lustrous",
    "whispered",
    "echoing",
    "forgotten",
    "otherworldly",
    "entangled",
    "enraptured",
    "forbidden",
    "untamed",
    "boundless",
    "infinite",
    "celestial",
    "abyssal",
    "venerable",
    "sacrosanct",
    "mirrored",
    "illustrious",
    "hidden",
    "unveiled",
    "serrated",
    "veiled",
    "skeletal",
    "reverberating",
    "silent",
    "gilded",
    "adamantine",
    "eldritch",
    "infernal",
    "sage",
    "hallowed",
    "cursed",
    "blessed",
    "vexed",
    "embered",
    "azure",
    "cerulean",
    "crimson",
    "scarlet",
    "viridescent",
    "opalescent",
    "pearlescent",
    "kohl-rimmed",
    "fey-touched",
    "tenebrous",
    "lambent",
    "candescent",
    "indigo",
    "molten",
    "frozen",
    "crackling",
    "humming",
    "throbbing",
    "pulsating",
    "shimmering",
    "swirling",
    "twisted",
    "gnarled",
    "sinuous",
    "coiled",
    "spiraled",
    "whirling",
    "winding",
    "undulating",
    "perpetual",
    "cataclysmic",
    "epochal",
    "anachronistic",
    "fleeting",
    "decaying",
    "withering",
    "blooming",
    "vibrating",
    "resonating",
    "quivering",
    "trembling",
    "oscillating",
    "quaking",
    "shaking",
    "shuddering",
    "vibrant",
    "piercing",
    "cutting",
    "slicing",
    "rending",
    "tearing",
    "shattering",
    "crushing",
    "smashing",
    "rending",
    "splintering",
    "shredding",
    "dissonant",
    "resonant",
    "cacophonic",
    "euphonic",
    "melodious",
    "harmonic",
    "discordant",
    "rhythmic",
    "symphonic",
    "atonal",
    "sonic",
    "ultrasonic",
    "infrasonic",
    "acoustic",
    "electronic",
    "electric",
    "magnetic",
    "gravitic",
    "kinetic",
    "thermal",
    "aetheric",
    "luminal",
    "subluminal",
    "transluminal",
]

nouns = [
    "forest",
    "cityscape",
    "mountain",
    "river",
    "castle",
    "robot",
    "garden",
    "desert",
    "ocean",
    "spaceship",
    "lighthouse",
    "waterfall",
    "blossom",
    "galaxy",
    "monolith",
    "ruins",
    "volcano",
    "moon",
    "statue",
    "wisp",
]

contexts = [
    "under the starry night",
    "at sunrise",
    "in the autumn",
    "under the rain",
    "in the winter",
    "during a thunderstorm",
    "in the fog",
    "in full bloom",
    "in the silence of night",
    "under a rainbow",
    "under the northern lights",
    "at the edge of the world",
    "amidst a meteor shower",
    "in the realm of dreams",
    "on a moonlit night",
    "during a solar eclipse",
    "at the end of a rainbow",
    "in the twilight hour",
    "beyond the cosmic veil",
    "at the dawn of time",
    "during high tide",
    "at sunset",
    "in the spring",
    "in the heat of summer",
    "in a blizzard",
    "during a hailstorm",
    "in a sandstorm",
    "in a whirlwind",
    "during a lunar eclipse",
    "at the stroke of midnight",
    "in the golden hour",
    "in the dead of winter",
    "in the height of noon",
    "during an earthquake",
    "in a volcanic eruption",
    "under a comet's tail",
    "at the crossroads",
    "in a time loop",
    "in a quantum state",
    "in the eye of the storm",
    "in the afterglow",
    "in the zenith",
    "in the nadir",
    "in a moment of serendipity",
    "in a fleeting instant",
    "in the abyss",
    "in the void",
    "in the limelight",
    "in the shadows",
    "amongst ancient ruins",
    "in a forgotten realm",
    "in a melting glacier",
    "on a crystal field",
    "in a frozen wasteland",
    "amidst a coral garden",
    "in a burning forest",
    "at the gates of a forgotten castle",
    "in the halls of a crystal palace",
    "on a pathway of floating stones",
    "in a city of clouds",
    "in a garden of singing flowers",
    "on a boat on a river of stars",
    "in a forest of giant mushrooms",
    "on a bridge of rainbows",
    "in a cave of wonders",
    "in a lair of dragons",
    "at the heart of a nebula",
    "in a village of whispers",
    "on the rings of Saturn",
    "in a theater of illusions",
    "on the wings of a storm",
    "in a valley of echoes",
    "at the fountain of youth",
    "on a canopy of endless trees",
    "in a desert of red sands",
    "in the labyrinth of reflections",
    "on the shores of oblivion",
    "in a city of endless towers",
    "on a sea of glass",
    "in a world without color",
    "in a realm of endless dusk",
    "in a never-ending waterfall",
    "at the cradle of creation",
    "in a field of floating orbs",
    "in a dimension of mirrors",
    "on the trail of falling stars",
    "in a land of forgotten lore",
    "in a reality of shifting sands",
    "on a mountain of whispers",
]

objects = [
    "ancient artifact",
    "floating clock",
    "enchanted book",
    "mysterious orb",
    "hovering ship",
    "magic wand",
    "crystal ball",
    "ethereal sword",
    "time machine",
    "golden chalice",
    "wind-up bird",
    "levitating stones",
    "talking mirror",
    "haunted painting",
    "teleportation gateway",
    "shimmering cloak",
    "enchanted locket",
    "crystal key",
    "phantom lantern",
    "celestial map",
    "magic quill",
    "dreamcatcher",
    "sacred scroll",
    "time-turning hourglass",
    "elixir vial",
    "astral projector",
    "dimensional cube",
    "quantum computer",
    "Terracotta Army artifact",
    "holographic display",
    "force field generator",
    "invisibility cloak",
    "telepathic helmet",
    "cybernetic arm",
    "android companion",
    "laser gun",
    "plasma sword",
    "jetpack",
    "anti-gravity boots",
    "virtual reality headset",
    "AI assistant",
    "biometric scanner",
    "genetic sequencer",
    "neural interface",
    "psychic crystal",
    "arcane grimoire",
    "tarot cards",
    "voodoo doll",
    "shamanic drum",
    "totem pole",
    "sacred feather",
    "holy relic",
    "cursed amulet",
    "wizard's hat",
    "alchemist's flask",
    "witch's broom",
    "spellbook",
    "magic carpet",
    "dragon egg",
    "mermaid scale",
    "goblin gold",
    "elfin bow",
    "dwarven axe",
    "vampire fang",
    "werewolf claw",
    "zombie antidote",
    "ghost trap",
    "demon seal",
    "angelic harp",
    "cosmic telescope",
    "interstellar beacon",
    "galactic passport",
    "asteroid sample",
    "black hole stabilizer",
    "wormhole key",
    "light saber",
    "one ring",
    "philosopher's stone",
    "excalibur",
    "mjolnir",
    "pandora's box",
    "ark of the covenant",
    "holy grail",
    "spear of destiny",
    "shroud of turin",
    "tablet of destiny",
    "book of the dead",
    "map of hidden treasures",
    "compass of fate",
    "hourglass of eternity",
    "mirror of illusions",
    "painting of the future",
    "statue of wisdom",
    "obelisk of power",
    "pyramid of enlightenment",
    "labyrinth of secrets",
    "maze of challenges",
    "garden of eden",
    "tree of life",
    "frozen flame",
    "singing sands",
    "whispering wind chime",
    "ever-changing tapestry",
    "never-ending notebook",
    "self-refilling goblet",
    "perpetual motion machine",
    "elixir of immortality",
    "gem of true seeing",
    "cloak of shadows",
    "helmet of invisibility",
    "goggles of night",
    "gloves of thieving",
    "boots of speed",
    "bottle of whispers",
    "amulet of the planes",
    "ring of regeneration",
    "belt of giant strength",
    "pendant of life saving",
    "quiver of endless arrows",
    "orb of storms",
    "lantern of revealing",
    "mirror of life trapping",
    "crown of command",
    "horn of blasting",
    "robe of stars",
    "vest of escape",
    "necklace of adaptation",
    "rune-engraved bones",
    "astronomer's lens",
    "sculptor's chisel",
    "painter's palette",
    "alchemist's crucible",
    "sorcerer's sigil",
    "pyromancer's tinderbox",
    "aquamancer's chalice",
    "geomancer's lodestone",
    "aeromancer's feather",
    "chronomancer's sundial",
    "necromancer's phylactery",
    "druid's seed pouch",
    "bard's tuning fork",
    "ranger's whistle",
    "paladin's holy symbol",
    "warrior's honing stone",
    "monk's prayer beads",
    "rogue's lockpick",
]

creatures = [
    "dragon",
    "unicorn",
    "phoenix",
    "griffin",
    "giant spider",
    "mermaid",
    "sphinx",
    "centaur",
    "fairy",
    "troll",
    "werewolf",
    "elemental spirit",
    "dancing tree",
    "gargoyle",
    "chimera",
    "dream weaver",
    "cosmic serpent",
    "lightning bird",
    "lunar moth",
    "stellar wolf",
    "solar deer",
    "aurora fox",
    "nebula whale",
    "celestial bear",
    "kraken",
    "yeti",
    "bigfoot",
    "sasquatch",
    "cyclops",
    "harpy",
    "minotaur",
    "basilisk",
    "siren",
    "nymph",
    "dryad",
    "salamander",
    "wyvern",
    "manticore",
    "banshee",
    "poltergeist",
    "djinn",
    "kelpie",
    "selkie",
    "wendigo",
    "vampire",
    "zombie",
    "ghost",
    "demon",
    "angel",
    "leviathan",
    "behemoth",
    "quetzalcoatl",
    "kitsune",
    "tanuki",
    "tengu",
    "kappa",
    "yokai",
    "oni",
    "naga",
    "asura",
    "rakshasa",
    "gorgon",
    "satyr",
    "pegasus",
    "hippogriff",
    "cockatrice",
    "will-o'-the-wisp",
    "pixie",
    "brownie",
    "leprechaun",
    "gnome",
    "dwarf",
    "elf",
    "orc",
    "goblin",
    "ogre",
]

characters = [
    "wizard",
    "adventurer",
    "princess",
    "astronaut",
    "robot",
    "pirate",
    "knight",
    "ninja",
    "explorer",
    "alien",
    "sorceress",
    "time traveler",
    "archaeologist",
    "samurai",
    "detective",
    "shaman",
    "warrior queen",
    "stargazer",
    "dream walker",
    "time weaver",
    "cosmonaut",
    "celestial mage",
    "comet chaser",
    "galactic guardian",
    "stellar scribe",
    "lunar lyricist",
    "interstellar wanderer",
    "shadow whisperer",
    "light bender",
    "reality shifter",
    "dimensional drifter",
    "chaos conjurer",
    "soul shepherd",
    "mind melder",
    "heart healer",
    "spirit summoner",
    "void voyager",
    "astral acrobat",
    "paradox priest",
    "maze master",
    "cybernetic centaur",
    "phoenix fire-dancer",
    "aqua adventurer",
    "thunder thrower",
    "wind whisperer",
    "stone sentinel",
    "crystal conjurer",
    "vortex vanquisher",
    "solar sorcerer",
    "frost forger",
    "nature nurturer",
    "volcanic vanguard",
    "tempest tamer",
    "quasar quester",
    "plasma phantom",
    "oceanic oracle",
    "titanic tree-tender",
    "meteoric marauder",
    "galaxy gladiator",
    "abyssal alchemist",
    "celestial cyclops",
    "dragon dreamer",
    "echo enchanter",
    "firework flinger",
    "gravity grappler",
    "horizon hunter",
    "ice illusionist",
    "jade juggler",
    "kinetic knight",
    "lava leviathan",
    "mystic mariner",
    "neon nomad",
    "optic overseer",
    "prismatic paladin",
    "quill quester",
    "rune raider",
    "spectrum sorcerer",
    "twilight tracker",
    "universal urchin",
    "vivid viking",
    "whirlwind warrior",
    "xenon xebec",
    "yielding yeti",
    "zenith zealot",
]

famous_characters = [
    "Robin Hood",
    "Zorro",
    "Dracula",
    "Sherlock Holmes",
    "John Carter",
    "Frankenstein's Monster",
    "Scarecrow",
    "Dorothy Gale",
    "Tin Woodman",
    "Cowardly Lion",
    "The Hunchback of Notre Dame",
    "King Kong",
    "Ivanhoe",
    "Alice (from Wonderland)",
    "Jack Pumpkinhead",
    "Gravestone",
    "Man of War",
    "Dr. Jekyll/Mr. Hyde",
    "Cthulhu",
    "Hercules",
    "Natty Bumppo",
    "White Rabbit",
    "Paul Bunyan",
    "Long John Silver",
    "Wizard Of Oz",
    "Firehair",
    "Captain Nemo",
    "King Arthur",
    "Woggle-Bug",
    "Mystico",
    "Cheshire Cat",
    "Wilhelmina Murray",
    "Queen Of Hearts",
    "Brad Spencer, Wonderman",
    "Mad Hatter",
    "Achilles",
    "Nyarlathotep",
    "Red Comet",
    "Allan Quatermain",
    "Atoman",
    "Helen of Troy",
    "Mouthpiece",
    "Moby Dick",
    "Wicked Witch of the West",
    "Victor Frankenstein",
    "Sinbad",
    "The Sphinx",
    "Headless Horseman",
    "Esau Cairn",
    "Abraham Van Helsing",
    "Ares",
    "Abdul Alhazred",
    "C. Auguste Dupin",
    "Ayesha",
    "Aladdin",
    "Barbarella",
    "Buddy",
    "Beowulf",
    "Bride of Frankenstein",
    "Captain Ahab",
    "Creature from the Black Lagoon",
    "Cyclone",
    "Dorian Gray",
    "Dagar, Desert Hawk",
    "Don Quixote",
    "Ebenezer Scrooge",
    "Gulliver",
    "Grendel",
    "Green Giant",
    "D'Artagnan",
    "Huckleberry Finn",
    "Aramis",
    "Porthos",
    "James Moriarty",
    "Judy of the Jungle",
    "Loch Ness Monster",
    "Moon Girl",
    "Magno",
    "Hugo Danner",
    "Green Lama",
    "Fighting Yank",
    "Octobriana",
    "Odysseus",
    "Scheherazade",
    "Red Riding Hood",
    "Rapunzel",
    "Rumpelstiltskin",
    "Rosie The Riveter",
    "Rocketgirl",
    "The Yellow Kid",
    "The Wolf Man",
    "Winnie-the-Pooh",
    "Anne (from 'Anne of Green Gables')",
    "Judah Ben-Hur (from 'Ben-Hur')",
    "Cinderella",
    "Mowgli",
    "The Phantom of the Opera",
    "Snow White",
    "Tarzan",
    "Oswald the Lucky Rabbit",
    "Felix the Cat",
    "Black Beauty",
    "Sara Crewe (from 'A Little Princess')",
    "The Nutcracker",
]

actions = [
    "exploring",
    "fighting",
    "dancing",
    "running",
    "flying",
    "singing",
    "dreaming",
    "casting a spell",
    "gazing at the stars",
    "writing in a journal",
    "navigating a map",
    "conjuring a storm",
    "playing an instrument",
    "ascending a staircase",
    "battling a beast",
    "traversing a tightrope",
    "unlocking a door",
    "swinging on a vine",
    "diving into water",
    "meditating",
    "reading a book",
    "drawing a sword",
    "crossing a bridge",
    "riding a creature",
    "solving a riddle",
    "weaving a tapestry",
    "mixing a potion",
    "building a fire",
    "carving a statue",
    "painting a mural",
    "harvesting herbs",
    "forging a weapon",
    "assembling a machine",
    "deciphering runes",
    "translating a text",
    "channeling energy",
    "balancing on a ledge",
    "climbing a tower",
    "scaling a mountain",
    "sailing a ship",
    "steering a spacecraft",
    "piloting a submarine",
    "floating in zero gravity",
    "teleporting",
    "time-traveling",
    "shape-shifting",
    "summoning spirits",
    "banishing demons",
    "healing the wounded",
    "rescuing captives",
    "disarming traps",
    "dodging arrows",
    "parrying attacks",
    "deflecting spells",
    "absorbing knowledge",
    "gathering resources",
    "crafting artifacts",
    "enhancing abilities",
    "training in combat",
    "studying magic",
    "breaching dimensions",
    "conjuring illusions",
    "evading capture",
    "navigating mazes",
    "orchestrating strategies",
    "unveiling mysteries",
    "wielding powers",
    "exorcising evil",
    "defying gravity",
    "embarking on quests",
    "unleashing potential",
    "bending reality",
    "transcending limits",
    "mending broken bonds",
    "discovering secrets",
    "nurturing growth",
    "facing fears",
    "embracing destiny",
    "maneuvering through danger",
    "overcoming obstacles",
    "trusting intuition",
    "captivating audiences",
    "leading a rebellion",
    "decoding enigma",
    "evoking emotions",
    "honoring the fallen",
    "safeguarding treasures",
    "beholding wonders",
    "eradicating curses",
    "manifesting dreams",
    "fostering alliances",
    "bestowing blessings",
    "judging the unjust",
    "unraveling the unknown",
    "pioneering innovations",
    "initiating rituals",
    "navigating through nightmares",
    "harmonizing with nature",
    "liberating the oppressed",
    "illuminating darkness",
    "quelling storms",
    "rekindling hope",
    "reveling in victory",
    "mourning losses",
    "communing with ancients",
    "interacting with relics",
    "contemplating the cosmos",
    "defending the innocent",
    "challenging fate",
    "wrestling with shadows",
    "sculpting destiny",
    "devising solutions",
    "embracing change",
    "charting uncharted",
    "unfurling sails of hope",
    "calibrating destinies",
    "vaulting through voids",
    "kindling the unknown",
    "quenching thirsts of curiosity",
    "embroidering the ephemeral",
    "cradling chaos",
    "entwining destinies",
    "reverberating through realms",
    "echoing through eternity",
    "harmonizing hymns of heroism",
    "embracing echoes of existence",
    "diving into daydreams",
    "sailing through starlight",
    "orchestrating omens",
    "reverberating rhythms of reality",
    "treading through time",
    "unfurling unfathomable",
    "vibrating through voids",
    "waltzing with whimsy",
    "x-raying xenon",
    "yielding to yonder",
    "zipping through zenith",
]


settings = [
    "castle",
    "forest",
    "cave",
    "oasis",
    "temple",
    "mansion",
    "station",
    "monastery",
    "ship",
    "city",
    "labyrinth",
    "garden",
    "clouds",
    "observatory",
    "sanctuary",
    "meadow",
    "lake",
    "valley",
    "island",
    "utopia",
    "desert",
    "volcano",
    "waterfall",
    "tundra",
    "swamp",
    "space station",
    "moon base",
    "jungle",
    "mountain peak",
    "underwater city",
    "glacier",
    "ruins",
    "haunted house",
    "farm",
    "beach",
    "skyscraper",
    "village",
    "amusement park",
    "zoo",
    "aquarium",
    "airport",
    "train station",
    "colosseum",
    "pyramid",
    "bazaar",
    "library",
    "museum",
    "school",
    "hospital",
    "prison",
    "fortress",
    "windmill",
    "lighthouse",
    "cathedral",
    "arena",
    "coral reef",
    "savanna",
    "rainforest",
    "canyon",
    "cliff",
    "marsh",
    "steppe",
    "battlefield",
    "dungeon",
    "mine",
    "factory",
    "floating island",
    "sky castle",
    "nebula",
    "black hole",
    "wasteland",
    "iceberg",
    "dimensional portal",
    "clocktower",
    "dojo",
    "igloo",
    "treehouse",
    "submarine",
    "spaceship",
    "casino",
    "theater",
    "opera house",
    "circus",
    "stadium",
    "mall",
    "arcade",
    "lunar colony",
    "asteroid mine",
    "alien planet",
    "magic shop",
    "wizard tower",
    "dragons lair",
    "eldritch realm",
    "fairy glen",
    "vampire castle",
    "werewolf den",
    "ghost town",
    "cyberpunk city",
    "steampunk factory",
    "post apocalyptic city",
    "underground bunker",
    "secret base",
    "nuclear silo",
    "abandoned asylum",
    "ancient temple",
    "sacred grove",
    "hobbit village",
    "elven city",
    "dwarven mine",
    "orc camp",
    "goblin market",
    "pirate ship",
    "robot factory",
    "virtual reality",
    "parallel universe",
    "quantum realm",
    "celestial palace",
    "infernal pit",
    "heavenly garden",
    "purgatory",
    "limbo",
    "nirvana",
    "shangri la",
    "atlantis",
    "eldorado",
    "avalon",
    "asgard",
    "olympus",
    "underworld",
    "valhalla",
    "middle earth",
    "galactic federation",
    "interstellar embassy",
    "wormhole",
    "pocket dimension",
    "haunted cemetery",
    "crypt",
    "mausoleum",
    "pet cemetery",
    "ancient ruins",
    "sphinx",
    "moai statues",
    "stonehenge",
    "chichen itza",
    "great wall",
    "taj mahal",
    "mount rushmore",
    "grand canyon",
    "niagara falls",
    "sahara desert",
    "everest basecamp",
    "north pole",
    "south pole",
    "deep sea trench",
    "bamboo forest",
    "cherry blossom grove",
    "lavender field",
    "sunflower field",
    "tea plantation",
    "coffee farm",
    "vineyard",
]

themes = [
    "Ghibli style",
    "Disney style",
    "Anime style",
    "Realistic style",
    "Abstract style",
    "Cubist style",
    "Surrealist style",
    "Art Deco style",
    "Pixel art style",
    "Minimalist style",
    "Graffiti style",
    "Dada style",
    "Fauvist style",
    "Constructivist style",
    "Futurist style",
    "Pointillist style",
    "Symbolist style",
    "Pre-Raphaelite style",
    "Byzantine style",
    "Steampunk style",
    "Cyberpunk style",
    "Manga style",
    "Film noir style",
    "Western style",
    "Psychedelic style",
    "Horror style",
    "Fantasy style",
    "Sci-Fi style",
    "Digital art style",
    "Analog film style",
    "3D style",
    "Comic style",
    "Low Poly style",
    "Vector style",
    "Chiaroscuro style",
    "Silhouette style",
    "Origami style",
    "Paper Cut-Out style",
    "Isometric style",
    "Wireframe style",
    "Blueprint style",
    "Sketch style",
    "Doodle style",
    "Zentangle style",
    "Mosaic style",
    "Stained Glass style",
    "Kaleidoscopic style",
    "Neon style",
    "Glitch Art style",
    "X-Ray style",
    "Solarised style",
    "Thermal Imaging style",
    "HDR style",
    "Lomography style",
    "Cross-Processing style",
    "Double Exposure style",
    "Bokeh style",
    "Tilt-Shift style",
    "Macabre style",
    "Goth style",
    "Punk style",
    "Retro style",
    "Retro-Futurist style",
]


STYLES = {
    "general": [
        {
            "model_path": "digiplay/Juggernaut_final",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "{theme} {famous_character} {action} on {setting} close-up, 8k, high quality",
                "negative": "bad quality, text",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 35,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "digiplay/Juggernaut_final",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "{theme} {object} {context} close-up, 8k, high quality",
                "negative": "bad quality, text",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 35,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "digiplay/Juggernaut_final",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "{theme} {creature} {action} {context} 8k, high quality",
                "negative": "bad quality, text",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 35,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "digiplay/Juggernaut_final",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "{theme} {character} {action} {context} close-up, 8k, high quality",
                "negative": "bad quality, text",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 35,
            "num_images": 1,
            "seed": -1,
        },
    ],
    "ghibli": [
        {
            "model_path": "nitrosocke/Ghibli-Diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "ghibli style {adjective} {setting} with {objects} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        # {
        #     "model_path": "nitrosocke/Ghibli-Diffusion",
        #     "model_scheduler": "euler_a",
        #     "prompt": {
        #         "positive": "ghibli style {adjective} {setting} with {adjective} {noun} {context}",
        #         "negative": "bad quality, text",
        #         "guidance_scale": 7,
        #     },
        #     "height": 688,
        #     "width": 512,
        #     "num_inference_steps": 50,
        #     "num_images": 1,
        #     "seed": -1,
        # },
        {
            "model_path": "nitrosocke/Ghibli-Diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "ghibli style {adjective} {setting} with a {character} {action} a {object} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "nitrosocke/Ghibli-Diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "ghibli style {adjective} {setting} with a {creature} {action} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
    ],
    "beksinski": [
        {
            "model_path": "s3nh/beksinski-style-stable-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "beksinski style {adjective} {setting} with {objects} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        # {
        #     "model_path": "s3nh/beksinski-style-stable-diffusion",
        #     "model_scheduler": "euler_a",
        #     "prompt": {
        #         "positive": "beksinski style {adjective} {setting} with {adjective} {noun} {context}",
        #         "negative": "bad quality, text",
        #         "guidance_scale": 7,
        #     },
        #     "height": 688,
        #     "width": 512,
        #     "num_inference_steps": 50,
        #     "num_images": 1,
        #     "seed": -1,
        # },
        {
            "model_path": "s3nh/beksinski-style-stable-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "beksinski style {adjective} {setting} with a {character} {action} a {object} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "s3nh/beksinski-style-stable-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "beksinski style {adjective} {setting} with a {creature} {action} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
    ],
    "inkpunk": [
        {
            "model_path": "Envvi/Inkpunk-Diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "nvinkpunk {adjective} {setting} with {objects} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        # {
        #     "model_path": "Envvi/Inkpunk-Diffusion",
        #     "model_scheduler": "euler_a",
        #     "prompt": {
        #         "positive": "nvinkpunk {adjective} {setting} with {adjective} {noun} {context}",
        #         "negative": "bad quality, text",
        #         "guidance_scale": 7,
        #     },
        #     "height": 688,
        #     "width": 512,
        #     "num_inference_steps": 50,
        #     "num_images": 1,
        #     "seed": -1,
        # },
        {
            "model_path": "Envvi/Inkpunk-Diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "nvinkpunk {adjective} {setting} with a {character} {action} a {object} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "Envvi/Inkpunk-Diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "nvinkpunk {adjective} {setting} with a {creature} {action} {context}",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
    ],
    "eldenring": [
        {
            "model_path": "nitrosocke/elden-ring-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "elden ring style {adjective} {setting} with {objects} {context}",
                "negative": "bad quality, text, card, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        # {
        #     "model_path": "nitrosocke/elden-ring-diffusion",
        #     "model_scheduler": "euler_a",
        #     "prompt": {
        #         "positive": "elden ring style {adjective} {setting} with {adjective} {noun} {context}",
        #         "negative": "bad quality, text, card",
        #         "guidance_scale": 7,
        #     },
        #     "height": 688,
        #     "width": 512,
        #     "num_inference_steps": 50,
        #     "num_images": 1,
        #     "seed": -1,
        # },
        {
            "model_path": "nitrosocke/elden-ring-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "elden ring style {adjective} {setting} with a {character} {action} a {object} {context}",
                "negative": "bad quality, text, card, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "nitrosocke/elden-ring-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "elden ring style {adjective} {setting} with a {creature} {action} {context}",
                "negative": "bad quality, text, card, landscape only",
                "guidance_scale": 7,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 50,
            "num_images": 1,
            "seed": -1,
        },
    ],
    "vangogh": [
        {
            "model_path": "dallinmackay/Van-Gogh-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "lvngvncnt {adjective} {setting} with {object} {context} close-up, 8k, highly detailed",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 6,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 25,
            "num_images": 1,
            "seed": -1,
        },
        # {
        #     "model_path": "dallinmackay/Van-Gogh-diffusion",
        #     "model_scheduler": "euler_a",
        #     "prompt": {
        #         "positive": "lvngvncnt {adjective} {setting} with {adjective} {noun} {context} 8k, highly detailed",
        #         "negative": "bad quality, text",
        #         "guidance_scale": 6,
        #     },
        #     "height": 688,
        #     "width": 512,
        #     "num_inference_steps": 25,
        #     "num_images": 1,
        #     "seed": -1,
        # },
        {
            "model_path": "dallinmackay/Van-Gogh-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "lvngvncnt {adjective} {setting} with a {character} {context} close-up, 8k, highly detailed",
                "negative": "bad quality, text, landscape only, orange",
                "guidance_scale": 6,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 25,
            "num_images": 1,
            "seed": -1,
        },
        {
            "model_path": "dallinmackay/Van-Gogh-diffusion",
            "model_scheduler": "euler_a",
            "prompt": {
                "positive": "lvngvncnt {adjective} {setting} with a {creature} {action} {context} close-up, 8k, highly detailed",
                "negative": "bad quality, text, landscape only",
                "guidance_scale": 6,
            },
            "height": 688,
            "width": 512,
            "num_inference_steps": 25,
            "num_images": 1,
            "seed": -1,
        },
    ],
}
