version: '3.8'

services:
  guexit_image_generation:
    build:
      context: .
      dockerfile: Dockerfile
    image: guexit_image_generation
    ports:
      - "5000:5000"
    environment:
      - CUDA_VERSION=11.7.1
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

secrets:
  git-credentials:
    file:  ~/.git-credentials
