version: '3.8'

services:
  image_generation:
    container_name: guexit_image_generation
    build:
      context: .
      dockerfile: Dockerfile
    image: guexit_image_generation
    ports:
      - "5001:5000"
    environment:
      - CUDA_VERSION=11.7.1
    env_file: .env

