python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the surrealism of dreams by Greg Rutkowski, highly detailed, high quality, surreal, dreamlike, abstract, bizarre, whimsical, imaginative" --negative_prompt "people, person, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "dreams" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the beauty of nature by Cyril Rolando, highly detailed, high quality, landscape, impressionistic, realistic, romantic, pastoral, idyllic" --negative_prompt "people, person, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "nature" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the journey of a hero by Cyril Rolando, highly detailed, high quality, epic fantasy, mythic, adventure, medieval, heroic, mythological" --negative_prompt "malformed faces, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "hero" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of a world of pure imagination by Cyril Rolando, highly detailed, high quality, whimsical, surreal, psychedelic, dreamlike, playful, fantastical" --negative_prompt "people, person, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "imagine" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the passage of time by Sparth, highly detailed, high quality, abstract, conceptual, minimalist, historical, nostalgic, introspective" --negative_prompt "signature, text, people, person, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "time" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the magic of childhood by Cyril Rolando, highly detailed, high quality, nostalgic, innocent, playful, whimsical, colorful, imaginative" --negative_prompt "malformed faces, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "child" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the power of love by Cyril Rolando, highly detailed, high quality, romantic, sentimental, emotional, expressive, dramatic, passionate" --negative_prompt "malformed faces, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "love" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the mysteries of the universe by Greg Rutkowski, highly detailed, high quality, cosmic, science fiction, futuristic, abstract, surreal, celestial" --negative_prompt "people, person, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "universe" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the triumph of the human spirit by Cyril Rolando, highly detailed, high quality, inspirational, motivational, uplifting, heroic, courageous, determined" --negative_prompt "malformed faces, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "human" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "creative illustration of the diversity of cultures by Cyril Rolando, highly detailed, high quality, multicultural, ethnic, traditional, historical, exotic, vibrant" --negative_prompt "malformed faces, malformed figures, bad quality" --guidance_scale 7 --height 688 --width 512 --num_images 20 --seed -1 --id "culture" &&
python3 image_generation/core/stable_diffusion.py --model_path stabilityai/stable-diffusion-2-1-base --positive_prompt "draw between two and five common objects style by Salvador Dali. minimalist objects, real-world objects, high quality, 4k" --negative_prompt "malformed objects, person, people, text, bad quality, signature" --guidance_scale 10 --height 688 --width 512 --num_images 20 --seed -1 --id "objects"