name: Docker Build, Test and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Extract version from pyproject.toml
        run: echo "LIB_VERSION=$(awk '/^\[tool.poetry\]/ {flag=1; next} /version/ && flag {print $3; flag=0}' pyproject.toml | tr -d '\"')" >> $GITHUB_ENV

      - name: Check Docker Version
        run: docker --version

      - name: Create .git-credentials file
        run: |
          echo "https://ugm2:${{ secrets.GH_TOKEN }}@github.com" > .git-credentials

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Release Notes from Changelog
        id: release_notes
        uses: CSchoel/release-notes-from-changelog@v1
        with:
          version: ${{ env.LIB_VERSION }}
          working-directory: .

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        run: |
          gh release create \
            -F "RELEASE_HEAD.md" \
            --title "Guexit.ImageGeneration v${{ env.LIB_VERSION }}" \
            ${{ env.LIB_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
