name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Docker Version
        run: docker --version

      - name: Check Docker Version
        run: docker --version

      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      - name: Check Docker Version
        run: docker --version

      - name: Check Docker Compose Version
        run: docker-compose --version

      - name: Build and run services
        run: |
          docker-compose up --build --d

      - name: Wait for services to start
        run: |
          sleep 10

      - name: Run tests
        run: |
          docker-compose exec guexit_image_generation sh -c "python -m unittest discover -s tests"
