name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Docker Version
        run: docker --version

      - name: Create .git-credentials file
        run: |
          echo "https://ugm2:${{ secrets.GH_TOKEN }}@github.com" > .git-credentials

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build . --secret id=git-credentials,src=.git-credentials -t ghcr.io/${{ github.repository }}/guexit_image_generation

      - name: Run tests
        run: |
          docker run -p 5000:5000 guexit_image_generation sh -c "poetry run tox"

      - name: Push to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}/guexit_image_generation
