name: Create Test VM (Ubuntu 22.04)

on:  # Adjust your trigger as needed
    workflow_dispatch:  # For manual triggering

jobs:
    create-vm:
        runs-on: ubuntu-latest 
        steps:
        - name: Chechout 
          uses: actions/checkout@v4
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
