name: Create Test VM (Ubuntu 22.04)

on: 
    workflow_dispatch:
    push:
      branches: 
        - deploy-image-generator-vm

jobs:
    create-vm:
        runs-on: ubuntu-latest 
        steps:
        - name: Chechout 
          uses: actions/checkout@v4
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
