name: Run Linting

on:
  workflow_call:
    outputs:
      commit-hash:
        description: 'Commit hash that passed the tests'
        value: ${{ jobs.build-and-run-tests.outputs.commit-hash }}
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Instal Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false

    - name: Install lint
      run: poetry install --only dev --sync

    - name: Run linting
      run: tox -e lint
