name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Instal Poetry
      run: |
        pip install -U pip
        pip install poetry
        pip show poetry

    - name: gh token
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github".insteadOf https://github

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run tests with coverage
      run: |
        poetry run coverage run -m unittest
        poetry run coverage report -i

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
