name: Run Tests

on:
  workflow_call:
    outputs:
      commit-hash:
        description: 'Commit hash that passed the tests'
        value: ${{ jobs.build-and-run-tests.outputs.commit-hash }}
    inputs:
      codecov_token:
        required: false
        type: string
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false

    - name: gh token
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github".insteadOf https://github

    - name: Install dependencies
      run: poetry install --with dev --sync

    - name: Run tests with coverage
      run: |
        tox -e test
        tox -e coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token != '' && inputs.codecov_token || secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: Output commit hash
      id: output-commit-hash
      run: |
        echo "commit-hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "All tests passed for commit '$(git rev-parse HEAD)'"
